package ua.nure.zabara.lab;

import ua.nure.zabara.hotel_itpoi.Room;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.Collection;
import java.util.List;
import java.util.Set;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "RoomServiceClient", targetNamespace = "http://server.zabara.nure.ua/")
/*@XmlSeeAlso({
    ObjectFactory.class
})*/
public interface TheService {


    /**
     * @param arg0
     * @return returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addRoom", targetNamespace = "http://server.zabara.nure.ua/", className = "ua.nure.zabara.lab.AddRoom")
    @ResponseWrapper(localName = "addRoomResponse", targetNamespace = "http://server.zabara.nure.ua/", className = "ua.nure.zabara.lab.AddRoomResponse")
    @Action(input = "http://server.zabara.nure.ua/RoomServiceClient/addRoom", output = "http://server.zabara.nure.ua/RoomServiceClient/addRoomResponse")
    public boolean addRoom(
            @WebParam(name = "arg0", targetNamespace = "")
                    Room arg0);

    /**
     * @param arg1
     * @param arg0
     * @return returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateRoom", targetNamespace = "http://server.zabara.nure.ua/", className = "ua.nure.zabara.lab.UpdateRoom")
    @ResponseWrapper(localName = "updateRoomResponse", targetNamespace = "http://server.zabara.nure.ua/", className = "ua.nure.zabara.lab.UpdateRoomResponse")
    @Action(input = "http://server.zabara.nure.ua/RoomServiceClient/updateRoom", output = "http://server.zabara.nure.ua/RoomServiceClient/updateRoomResponse")
    public boolean updateRoom(
            @WebParam(name = "arg0", targetNamespace = "")
                    int arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    Room arg1);

    /**
     * @param arg0
     * @return returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteRoom", targetNamespace = "http://server.zabara.nure.ua/", className = "ua.nure.zabara.lab.DeleteRoom")
    @ResponseWrapper(localName = "deleteRoomResponse", targetNamespace = "http://server.zabara.nure.ua/", className = "ua.nure.zabara.lab.DeleteRoomResponse")
    @Action(input = "http://server.zabara.nure.ua/RoomServiceClient/deleteRoom", output = "http://server.zabara.nure.ua/RoomServiceClient/deleteRoomResponse")
    public boolean deleteRoom(
            @WebParam(name = "arg0", targetNamespace = "")
                    int arg0);

    /**
     * @param arg0
     * @return returns java.util.List<org.example.ua.nure.zabara.hotel_itpoi.Room>
     */
//    @WebMethod
//    @WebResult(targetNamespace = "")
////    @RequestWrapper(localName = "getRoomsByFilterFromBusinessLayer", targetNamespace = "http://server.zabara.nure.ua/", className = "ua.nure.zabara.lab.GetRoomsByFilterFromBusinessLayer")
//    @ResponseWrapper(localName = "getRoomsByFilterFromBusinessLayerResponse", targetNamespace = "http://server.zabara.nure.ua/", className = "ua.nure.zabara.lab.GetRoomsByFilterFromBusinessLayerResponse")
//    @Action(input = "http://server.zabara.nure.ua/RoomService/getRoomsByFilterFromBusinessLayerRequest", output = "http://server.zabara.nure.ua/RoomService/getRoomsByFilterFromBusinessLayerResponse")
//    public List<Room> getRoomsByFilterFromBusinessLayer(
//            @WebParam(name = "arg0", targetNamespace = "")
//                    String arg0);

    /**
     * @return returns java.util.List<org.example.ua.nure.zabara.hotel_itpoi.Room>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRoomsFromBusinessLayer", targetNamespace = "http://server.zabara.nure.ua/", className = "ua.nure.zabara.lab.GetRoomsFromBusiness")
    @ResponseWrapper(localName = "getRoomsFromBusinessLayerResponse", targetNamespace = "http://server.zabara.nure.ua/", className = "ua.nure.zabara.lab.GetRoomsFromBusinessResponse")
    @Action(input = "http://server.zabara.nure.ua/RoomServiceClient/getRoomsFromBusinessLayer", output = "http://server.zabara.nure.ua/RoomServiceClient/getRoomsFromBusinessLayerResponse")
    public Collection<Room> getRoomsFromBusinessLayer();

}
