
package server.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.4
 * Thu Feb 11 15:07:28 EET 2016
 * Generated source version: 3.1.4
 */

@XmlRootElement(name = "updateRoomCount", namespace = "http://service.ua.nure.zabara.server.order.nure.ua/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "updateRoomCount", namespace = "http://service.ua.nure.zabara.server.order.nure.ua/", propOrder = {"id", "count"})

public class UpdateRoomCount {

    @XmlElement(name = "id")
    private int id;
    @XmlElement(name = "count")
    private int count;

    public int getId() {
        return this.id;
    }

    public void setId(int newId)  {
        this.id = newId;
    }

    public int getCount() {
        return this.count;
    }

    public void setCount(int newCount)  {
        this.count = newCount;
    }

}

